python IP_multiview_features_generation.py  "1"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "1"
python IP_multiview_features_generation.py  "2"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "2"
python IP_multiview_features_generation.py  "3"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "3"
python IP_multiview_features_generation.py  "4"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "4"
python IP_multiview_features_generation.py  "5"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "5"
python IP_multiview_features_generation.py  "6"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "6"
python IP_multiview_features_generation.py  "7"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "7"
python IP_multiview_features_generation.py  "8"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "8"
python IP_multiview_features_generation.py  "9"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "9"
python IP_multiview_features_generation.py  "10"
python train_RN_FT_IP_RESNET.py --index 0
python test_RN_IP_RESNET.py --index 0
python train_RN_FT_IP_RESNET.py --index 1
python test_RN_IP_RESNET.py --index 1
python train_RN_FT_IP_RESNET.py --index 2
python test_RN_IP_RESNET.py --index 2
python train_RN_FT_IP_RESNET.py --index 3
python test_RN_IP_RESNET.py --index 3
python train_RN_FT_IP_RESNET.py --index 4
python test_RN_IP_RESNET.py --index 4
python train_RN_FT_IP_RESNET.py --index 5
python test_RN_IP_RESNET.py --index 5
python train_RN_FT_IP_RESNET.py --index 6
python test_RN_IP_RESNET.py --index 6
python train_RN_FT_IP_RESNET.py --index 7
python test_RN_IP_RESNET.py --index 7
python train_RN_FT_IP_RESNET.py --index 8
python test_RN_IP_RESNET.py --index 8
python train_RN_FT_IP_RESNET.py --index 9
python test_RN_IP_RESNET.py --index 9
python result_IP.py "10"
